### ISSUE TITLE
[Question] tinyupload link issue?

### ISSUE THREAD

**Issue by ChrisMaitland** [Vjww/GpwEditor#6]
Hi, First of all, impressive work! Just wanted to check if there was an issue with the installer download link, as it seems to timeout on different browsers?

**Comment by Vjww** [comment]
Thank you.  Plenty of work still to be done!

Apologies, I have now updated the readme file as the link has expired.

As GPW Edit v1,1 has a significant bug, I suggest you download v1.0 to enjoy the game.

https://github.com/Vjww/GpwEditor/releases/download/v1.0.0/GpwEdit_1_0_0_0.zip

You may also require the .NET Framework 4.6.1 to run this version of the editor.

https://www.microsoft.com/en-us/download/details.aspx?id=49982
